#!/usr/bin/env bash
# Fetch/build the Android native dependencies into the gen/android jniLibs:
#   - xray-core (Android arm64) -> libxray.so   (exec'd from nativeLibraryDir)
#   - hev-socks5-tunnel (tun2socks) -> libhev-socks5-tunnel.so (+ its header)
# These are large/binary, so they're gitignored and (re)generated by this
# script. Requires the Android NDK (ANDROID_NDK_HOME / NDK_HOME). Run from the
# project root.
set -euo pipefail

XRAY_VER="26.6.27"
ABI="arm64-v8a"
ROOT="$(pwd)"
JNI="$ROOT/src-tauri/gen/android/app/src/main/jniLibs/$ABI"
JNI_SRC="$ROOT/src-tauri/gen/android/app/src/main/jni"
NDK="${ANDROID_NDK_HOME:-${NDK_HOME:-}}"

mkdir -p "$JNI" "$JNI_SRC/hev-include"

# --- xray (Android arm64) ---
if [ ! -f "$JNI/libxray.so" ]; then
  echo "fetching xray-core $XRAY_VER (android arm64)…"
  TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
  curl -fsSL -o "$TMP/x.zip" \
    "https://github.com/XTLS/Xray-core/releases/download/v${XRAY_VER}/Xray-android-arm64-v8a.zip"
  unzip -o -q "$TMP/x.zip" xray -d "$TMP"
  install -m 0755 "$TMP/xray" "$JNI/libxray.so"
fi

# --- hev-socks5-tunnel (tun2socks) ---
if [ ! -f "$JNI/libhev-socks5-tunnel.so" ]; then
  [ -n "$NDK" ] || { echo "set ANDROID_NDK_HOME or NDK_HOME"; exit 1; }
  echo "building hev-socks5-tunnel (tun2socks)…"
  T2S="$(mktemp -d)"
  git clone --recursive --depth 1 https://github.com/heiher/hev-socks5-tunnel "$T2S"
  ( cd "$T2S" && "$NDK/ndk-build" NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk \
      NDK_APPLICATION_MK=./Application.mk APP_ABI="$ABI" APP_PLATFORM=android-24 -j4 )
  install -m 0644 "$T2S/libs/$ABI/libhev-socks5-tunnel.so" "$JNI/libhev-socks5-tunnel.so"
  # dereference the header symlink for the JNI shim's include
  cp -L "$T2S/include/hev-socks5-tunnel.h" "$JNI_SRC/hev-include/hev-socks5-tunnel.h"
  rm -rf "$T2S"
fi

echo "android native libs ready in $JNI"
